# Análise Exploratória de Dados - Base Varejo

## Importação das bibliotecas e configurações

In [76]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2F}'.format)

print("✅ Pronto! Bibliotecas carregadas.")
print(f"   Versão do pandas: {pd.__version__}")

✅ Pronto! Bibliotecas carregadas.
   Versão do pandas: 3.0.3

## Importação da base de dados  e  Visualização Inicial da Base

In [77]:
import pandas as pd

df = pd.read_csv('../data/Base Varejo.csv',sep=';',encoding='latin-1')
print("Prinmeiras linhas do dataset:")
df.head(10)

Prinmeiras linhas do dataset:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,01/02/2019,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,01/02/2019,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,01/02/2019,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN

## Verificando os tipos dos dados e numero de linhas e colunas

In [78]:

print(f" O dataset tem {df.shape[0]} linhas e {df.shape[1]} colunas")
print()
print(" Tipo de dado de cada coluna:")
print(df.dtypes)

 O dataset tem 830000 linhas e 14 colunas

 Tipo de dado de cada coluna:
DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## Estutura da Base de dados

In [79]:
def diagnostico(df, nome="DataFrame"):
 
    print("=" * 55)
   
    print(f"   DIAGNÓSTICO: {nome}")
    print("=" * 55)
    print(f"  Linhas:           {df.shape[0]:,}")
    print(f"  Colunas:          {df.shape[1]}")
    print(f"  Linhas duplicadas:{df.duplicated().sum():,}")
    print()
    
    nulos = df.isnull().sum()
    pct   = (nulos / len(df) * 100).round(1)
    
    print("  Coluna           | Tipo       | Nulos | % Nulos")
    print("  " + "-"*50)
    for col in df.columns:
        tipo = str(df[col].dtype)
        print(f"  {col:<18}| {tipo:<10} | {nulos[col]:<5} | {pct[col]}%")
    print("=" * 55)


diagnostico(df, "Base Varejo")

=======================================================
   DIAGNÓSTICO: Base Varejo
=======================================================
  Linhas:           830,000
  Colunas:          14
  Linhas duplicadas:96,553

  Coluna           | Tipo       | Nulos | % Nulos
  --------------------------------------------------
  DATA              | str        | 0     | 0.0%
  CO_ID             | int64      | 0     | 0.0%
  CL_ID             | int64      | 0     | 0.0%
  CL_GENERO         | str        | 0     | 0.0%
  CL_EC             | int64      | 0     | 0.0%
  CL_FHL            | int64      | 0     | 0.0%
  CL_SEG            | str        | 0     | 0.0%
  PR_ID             | int64      | 0     | 0.0%
  PR_CAT            | str        | 0     | 0.0%
  PR_NOME           | str        | 0     | 0.0%
  Unnamed: 10       | float64    | 830000 | 100.0%
  Unnamed: 11       | float64    | 830000 | 100.0%
  Unnamed: 12       | float64    | 830000 | 100.0%
  Unnamed: 13       | float64    | 830000 | 100.0%
=======================================================

## Análise do Diagnóstico

A base possui **830.000 registros** e **14 colunas**, representando informações de compras, clientes e produtos do varejo.


Foram identificadas quatro colunas com valores faltantes:

| Coluna | Valores nulos | % de nulos |
|---------|---------:|---------:|
| Unnamed: 10 | 830.000 | 100% |
| Unnamed: 11 | 830.000 | 100% |
| Unnamed: 12 | 830.000 | 100% |
| Unnamed: 13 | 830.000 | 100% |

As demais colunas não apresentam valores nulos.

 Foram identificados **96.553 registros duplicados**, o que representa uma quantidade significativa da base. Esses registros deverão ser avaliados e removidos durante a etapa de limpeza dos dados para evitar distorções nas análises.


Em geral, os tipos de dados estão adequados para as variáveis numéricas e categóricas. Entretanto, a coluna **DATA** foi importada como texto (`str`) e deverá ser convertida para o tipo `datetime`, permitindo análises temporais mais precisas.

Além disso, as colunas **Unnamed: 10**, **Unnamed: 11**, **Unnamed: 12** e **Unnamed: 13** apresentam 100% de valores nulos, indicando que provavelmente foram importadas indevidamente e deverão ser removidas na etapa de limpeza.

#### Verificação de Registros Duplicados

In [80]:
duplicados = df[df.duplicated()]

duplicados.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN

### Principais Problemas Identificados na Base

- Existência de colunas totalmente vazias (Unnamed).
- Coluna DATA importada como texto (string).
- Presença de registros duplicados na base.

## Limpeza dos dados

### Remoção de Registros com Valores Ausentes

Remoção de registros ou colunas por apresentar 100% de valores ausentes

In [81]:
nulos = df.isnull().sum()

print("Colunas com valores ausentes:")
print(nulos[nulos > 0])

Colunas com valores ausentes:
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [82]:
df = df.dropna(axis=1, how='all')

print("Dimensões após remoção das colunas vazias:")
print(df.shape)

Dimensões após remoção das colunas vazias:
(830000, 10)

In [83]:
nulos = df.isnull().sum()

print("Colunas com valores ausentes:")
print(nulos[nulos > 0])

Colunas com valores ausentes:
Series([], dtype: int64)

### Analise das duplicatas

In [84]:
print(f"Linhas completamente iguais: {df.duplicated().sum()}")

print(f"Compras duplicadas (CO_ID): {df.duplicated(subset=['CO_ID']).sum()}")

print(df[df.duplicated(subset=['CO_ID'], keep=False)].head())

Linhas completamente iguais: 96553
Compras duplicadas (CO_ID): 811529
         DATA  CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID     PR_CAT  \
0  01/02/2019   1000    534         M      4       1      C     67    BEBIDAS
1  01/02/2019   1000    534         M      4       1      C     70    BEBIDAS
2  01/02/2019   1000    534         M      4       1      C    178    HIGIENE
3  01/02/2019   1000    534         M      4       1      C      4  ALIMENTOS
4  01/02/2019   1000    534         M      4       1      C    175    LIMPEZA

                PR_NOME
0  REFRIGERANTE GUARANA
1   REFRIGERANTE OUTROS
2       LENCO UMEDECIDO
3               ABACAXI
4     LIMPADOR MULTIUSO

### Validação da Regra de Negócio do Identificador de Compra (CO_ID)

In [85]:
print(f"Quantidade de registros: {len(df)}")
print(f"Quantidade de compras únicas: {df['CO_ID'].nunique()}")
print(f"Registros com CO_ID repetido: {df.duplicated(subset=['CO_ID']).sum()}")

Quantidade de registros: 830000
Quantidade de compras únicas: 18471
Registros com CO_ID repetido: 811529

A base possui 733.447 registros e 18.471 compras únicas identificadas pela coluna CO_ID.

Foram encontrados 714.976 registros com CO_ID repetido. Entretanto, essa repetição não caracteriza necessariamente uma duplicata, pois uma mesma compra pode conter vários produtos diferentes registrados em linhas distintas.

Dessa forma, os registros com CO_ID repetido foram mantidos na base, sendo removidas apenas as linhas completamente idênticas identificadas durante a etapa de tratamento de duplicatas.

### Remoção de duplicatas

In [86]:
# Verificando duplicatas reais (linhas totalmente iguais)
print(f"Linhas completamente iguais: {df.duplicated().sum()}")
print()

# Visualizando algumas duplicatas (caso existam)
print("Exemplo de linhas duplicadas:")
print(df[df.duplicated(keep=False)].head())
print()

# Removendo duplicatas
df = df.drop_duplicates()

print("Após remoção:")
print(f"Linhas duplicadas restantes: {df.duplicated().sum()}")
print(f"Linhas finais do dataset: {df.shape[0]}")

Linhas completamente iguais: 96553

Exemplo de linhas duplicadas:
          DATA  CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID  \
3   01/02/2019   1000    534         M      4       1      C      4
7   01/02/2019   1000    534         M      4       1      C     11
14  01/02/2019   1000    534         M      4       1      C     13
15  01/02/2019   1000    534         M      4       1      C    218
19  01/02/2019   1000    534         M      4       1      C     13

       PR_CAT             PR_NOME
3   ALIMENTOS             ABACAXI
7   ALIMENTOS              AZEITE
14  ALIMENTOS              BANANA
15  ALIMENTOS  BIFE DE COXAO MOLE
19  ALIMENTOS              BANANA

Após remoção:
Linhas duplicadas restantes: 0
Linhas finais do dataset: 733447

Foram identificadas linhas completamente duplicadas na base de dados.  
Esses registros foram removidos para evitar distorções nas análises.

## Limpeza da categoria

In [87]:
if df['PR_CAT'].isnull().sum()> 0:
    df['PR_CAT'] = df['PR_CAT'].fillna("SEM CATEGORIA")
    print("Nulos em 'PR_CAT' preenchidos com 'SEM CATEGORIA'")

elif (df['PR_CAT'] == '#N/D').sum()>0:
    df['PR_CAT'] = df['PR_CAT'].replace('#N/D', 'SEM CATEGORIA')
    print("Valores '#N/D' em 'PR_CAT' substituídos por 'SEM CATEGORIA'")

else:
    print("PR_CAT já esta preenchida corretamente")

Valores '#N/D' em 'PR_CAT' substituídos por 'SEM CATEGORIA'

### Transformando data de string para datetime

In [88]:
df['DATA'] = pd.to_datetime(df['DATA'], dayfirst=True, errors='coerce')

In [89]:
df['DATA'].info()

<class 'pandas.Series'>
Index: 733447 entries, 0 to 829999
Series name: DATA
Non-Null Count   Dtype
--------------   -----
733447 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 11.2 MB

## Criando base final tratada para análise

In [90]:
df.to_csv('../data/Base_Varejo_Limpa.csv', index=False, sep=';')
print("Base limpa salva com sucesso.")

Base limpa salva com sucesso.

## Estatísticas Descritivas da Coluna CL_FHL

In [91]:
df['CL_FHL'].describe()

count   733447.00
mean         1.15
std          1.42
min          0.00
25%          0.00
50%          0.00
75%          2.00
max          4.00
Name: CL_FHL, dtype: float64

## Calculo Estatísticas descritivas

In [93]:
print("Media:", df['CL_FHL'].mean())
print("Mediana:", df['CL_FHL'].median())
print("Desvio Padrão:", df['CL_FHL'].std())
print("Moda:", df['CL_FHL'].mode()[0])
print("Mínimo:", df['CL_FHL'].min())
print("Máximo:", df['CL_FHL'].max())
print()

print("Quartis:")
print(df['CL_FHL'].quantile([0.25, 0.5, 0.75]))

Media: 1.1460487260838206
Mediana: 0.0
Desvio Padrão: 1.4169173697917072
Moda: 0
Mínimo: 0
Máximo: 4

Quartis:
0.25   0.00
0.50   0.00
0.75   2.00
Name: CL_FHL, dtype: float64