# Análise Exploratória de Dados - Base Varejo

## Importação das bibliotecas e configurações

In [43]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2F}'.format)

print("✅ Pronto! Bibliotecas carregadas.")
print(f"   Versão do pandas: {pd.__version__}")

✅ Pronto! Bibliotecas carregadas.
   Versão do pandas: 3.0.3

## Importação da base de dados  e  Visualização Inicial da Base

In [44]:
import pandas as pd

df = pd.read_csv('../data/Base Varejo.csv',sep=';',encoding='latin-1')
print("Prinmeiras linhas do dataset:")
df.head(10)

Prinmeiras linhas do dataset:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,01/02/2019,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,01/02/2019,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,01/02/2019,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN

## Verificando os tipos dos dados e numero de linhas e colunas

In [45]:

print(f" O dataset tem {df.shape[0]} linhas e {df.shape[1]} colunas")
print()
print(" Tipo de dado de cada coluna:")
print(df.dtypes)

 O dataset tem 830000 linhas e 14 colunas

 Tipo de dado de cada coluna:
DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## Estutura da Base de dados

In [46]:
def diagnostico(df, nome="DataFrame"):
 
    print("=" * 55)
    print(f"  📊 DIAGNÓSTICO: {nome}")
    print("=" * 55)
    print(f"  Linhas:           {df.shape[0]:,}")
    print(f"  Colunas:          {df.shape[1]}")
    print(f"  Linhas duplicadas:{df.duplicated().sum():,}")
    print()
    
    nulos = df.isnull().sum()
    pct   = (nulos / len(df) * 100).round(1)
    
    print("  Coluna           | Tipo       | Nulos | % Nulos")
    print("  " + "-"*50)
    for col in df.columns:
        tipo = str(df[col].dtype)
        print(f"  {col:<18}| {tipo:<10} | {nulos[col]:<5} | {pct[col]}%")
    print("=" * 55)


diagnostico(df, "Base Varejo")

=======================================================
  📊 DIAGNÓSTICO: Base Varejo
=======================================================
  Linhas:           830,000
  Colunas:          14
  Linhas duplicadas:96,553

  Coluna           | Tipo       | Nulos | % Nulos
  --------------------------------------------------
  DATA              | str        | 0     | 0.0%
  CO_ID             | int64      | 0     | 0.0%
  CL_ID             | int64      | 0     | 0.0%
  CL_GENERO         | str        | 0     | 0.0%
  CL_EC             | int64      | 0     | 0.0%
  CL_FHL            | int64      | 0     | 0.0%
  CL_SEG            | str        | 0     | 0.0%
  PR_ID             | int64      | 0     | 0.0%
  PR_CAT            | str        | 0     | 0.0%
  PR_NOME           | str        | 0     | 0.0%
  Unnamed: 10       | float64    | 830000 | 100.0%
  Unnamed: 11       | float64    | 830000 | 100.0%
  Unnamed: 12       | float64    | 830000 | 100.0%
  Unnamed: 13       | float64    | 830000 | 100.0%
=======================================================

## Análise do Diagnóstico

A base possui **830.000 registros** e **14 colunas**, representando informações de compras, clientes e produtos do varejo.


Foram identificadas quatro colunas com valores faltantes:

| Coluna | Valores nulos | % de nulos |
|---------|---------:|---------:|
| Unnamed: 10 | 830.000 | 100% |
| Unnamed: 11 | 830.000 | 100% |
| Unnamed: 12 | 830.000 | 100% |
| Unnamed: 13 | 830.000 | 100% |

As demais colunas não apresentam valores nulos.

 Foram identificados **96.553 registros duplicados**, o que representa uma quantidade significativa da base. Esses registros deverão ser avaliados e removidos durante a etapa de limpeza dos dados para evitar distorções nas análises.


Em geral, os tipos de dados estão adequados para as variáveis numéricas e categóricas. Entretanto, a coluna **DATA** foi importada como texto (`str`) e deverá ser convertida para o tipo `datetime`, permitindo análises temporais mais precisas.

Além disso, as colunas **Unnamed: 10**, **Unnamed: 11**, **Unnamed: 12** e **Unnamed: 13** apresentam 100% de valores nulos, indicando que provavelmente foram importadas indevidamente e deverão ser removidas na etapa de limpeza.

#### Verificação de Registros Duplicados

### Visualização dos Registros Duplicados

In [47]:
duplicados = df[df.duplicated()]

duplicados.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN

### Principais Problemas Identificados na Base

- Existência de colunas totalmente vazias (Unnamed).
- Coluna DATA importada como texto (string).
- Presença de registros duplicados na base.