# Análise Exploratória de Dados - Base Varejo

## Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np

## Importação da base de dados

In [23]:
import pandas as pd

df = pd.read_csv('../data/Base Varejo.csv',sep=';',encoding='latin-1')

## Visualização Inicial da Base

In [15]:
df.head()

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

## Estutura da Base de dados

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

## Quantidade de linhas e colunas

In [26]:
print(f'Quantidade de linhas: {df.shape[0]}')
print(f'Quantidade de colunas: {df.shape[1]}')

Quantidade de linhas: 830000
Quantidade de colunas: 14

## Estutura da Base de dados

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

## Visualizar nomes das colunas

In [28]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='str')

#### Verificação de Valores Nulos

In [29]:
df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

#### Verificação de Registros Duplicados

In [30]:
df.duplicated().sum()

np.int64(96553)

### Visualização dos Registros Duplicados

In [31]:
duplicados = df[df.duplicated()]

duplicados.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN

### Principais Problemas Identificados na Base

- Existência de colunas totalmente vazias (Unnamed).
- Coluna DATA importada como texto (string).
- Presença de registros duplicados na base.

## Convertendo a data que está em string

In [32]:
df['DATA'] = pd.to_datetime(df['DATA'], errors='coerce')

## Verificando resultado

In [33]:
df['DATA'].info()

<class 'pandas.Series'>
RangeIndex: 830000 entries, 0 to 829999
Series name: DATA
Non-Null Count   Dtype
--------------   -----
345265 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 6.3 MB